variables:
  ###########################################################################################################################
  ################################################## Common Variables #######################################################
  ###########################################################################################################################

  ######################################
  # Agent settings
  ######################################

  vmImage: 'ubuntu-latest' # Use this for Microsoft-hosted agents
  poolName: '' # Use this for self-hosted agents

  ######################################
  # Validation deployment settings
  ######################################

  location: 'EastUS' # The default location to test deploy resources to

  ######################################
  # global tokens settings
  ######################################

  # this determines the starting prefix and ending suffix of the token in your file.
  tokenPrefix: '<<'
  tokenSuffix: '>>'