# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 2 - NoOps Accelerator - Roles GitHub Actions deployment pipeline

on:
  workflow_dispatch:
    inputs:
      environmentName:
        type: string
        description: Environment name (optional), e.g. MLZ-main
        required: false

defaults:
  run:
    shell: pwsh
    working-directory: src/bicep/scripts/LZ-Mgmt/deployments

jobs:
  roles:
    name: Roles

    strategy:
      matrix:
        roleName:
          - la-vminsights-readonly
          - lz-appowner
          - lz-netops
          - lz-secops
          - lz-subowner
      fail-fast: false

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure PowerShell modules
      run: |
        Install-Module Az -Force
        Install-Module powershell-yaml -Force
    - name: Deploy Roles
      run: |
        ./RunNoOpsWorkflows.ps1 `
          -DeployLandingZoneRoles `
          -RoleNames '${{ matrix.roleName }}' `
          -EnvironmentName '${{github.event.inputs.environmentName}}' `
          -LoginServicePrincipalJson (ConvertTo-SecureString -String '${{secrets.NOOPS_CREDENTIALS}}' -AsPlainText -Force) `
          -GitHubRepo ${env:GITHUB_REPOSITORY} `
          -GitHubRef ${env:GITHUB_REF}