# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, 
# EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES 
# OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
# ----------------------------------------------------------------------------------

name: 4 - NoOps Accelerator - Mission Landing Zone GitHub Actions deployment pipeline

on:
  workflow_dispatch:
    inputs:      
      subscriptionIds:
        type: string
        description: Subscription ID(s) (optional), e.g. "abcd", "1234"
        required: false
      environmentName:
        type: string
        description: Environment name (optional), e.g. MLZ-main
        required: false
  
defaults:
  run:
    shell: pwsh
    working-directory: src/bicep/scripts/LZ-Mgmt/deployments

jobs:
  